#!/bin/bash
set -e

echo "========================================="
echo "1. Training NeRF Model on 0726 Metric Dataset"
echo "========================================="
# Disabling all auto-scaling and auto-orientation to preserve absolute metric world coordinates
.venv_nerf/bin/ns-train nerfacto \
    --max-num-iterations 2000 \
    --data captures_0726_nerf_metric \
    --output-dir outputs_0726_metric \
    --vis tensorboard \
    nerfstudio-data \
    --downscale-factor 1 \
    --orientation-method none \
    --center-method none \
    --auto-scale-poses False
echo ""

echo "========================================="
echo "2. Exporting Cropped Point Cloud"
echo "========================================="
# Automatically find the latest config.yml generated by the training run
CONFIG_PATH=$(find outputs_0726_metric/captures_0726_nerf_metric/nerfacto -name "config.yml" | sort | tail -n 1)

if [ -z "$CONFIG_PATH" ]; then
    echo "Error: Could not find config.yml. Did training fail?"
    exit 1
fi

echo "Found latest training config: $CONFIG_PATH"
echo "Running tightly cropped point cloud export..."

# Bounding box is exactly 30cm (0.3 meters) to capture the 15cm clay object
.venv_nerf/bin/ns-export pointcloud \
    --load-config "$CONFIG_PATH" \
    --output-dir exports/0726_metric_pc_cropped \
    --num-points 1000000 \
    --remove-outliers True \
    --normal-method open3d \
    --obb-center 0.0 0.0 0.0 \
    --obb-scale 0.3 0.3 0.3 \
    --obb-rotation 0.0 0.0 0.0

echo ""
echo "========================================="
echo "3. Filtering Point Cloud (SOR)"
echo "========================================="
.venv_nerf/bin/python tools/nerf/filter_cloud.py \
    --input exports/0726_metric_pc_cropped/point_cloud.ply \
    --output exports/0726_metric_pc_cropped/point_cloud_filtered.ply

echo "========================================="
echo "Pipeline complete! Final filtered mesh saved to exports/0726_metric_pc_cropped/point_cloud_filtered.ply"
echo "========================================="
