#!/bin/bash
set -e

echo "========================================="
echo "0. Undistorting and Generating Masks (Scale 4x)"
echo "========================================="
.venv_nerf/bin/python tools/prepare_images_and_masks.py --calib captures_8-13_three_flat_calibrated/calibration_results.json --img_dir data/three_flat_real_calib/images --out_dir data/three_flat_real_calib --scale 4
echo ""

echo "========================================="
echo "1. Generating transforms.json"
echo "========================================="
.venv_nerf/bin/python tools/generate_nerf_transforms.py --calib captures_8-13_three_flat_calibrated/calibration_results.json --output data/three_flat_real_calib/transforms.json --scale 4.0
echo "Successfully generated data/three_flat_real_calib/transforms.json"
echo ""

echo "========================================="
echo "2. Training NeRF Model"
echo "========================================="
# Disabling all auto-scaling and auto-orientation to preserve absolute metric world coordinates
.venv_nerf/bin/ns-train nerfacto \
    --max-num-iterations 2000 \
    --data data/three_flat_real_calib \
    --output-dir outputs_three_flat \
    --vis tensorboard \
    nerfstudio-data \
    --downscale-factor 1 \
    --orientation-method none \
    --center-method none \
    --auto-scale-poses False
echo ""

echo "========================================="
echo "3. Exporting Cropped Point Cloud"
echo "========================================="
# Automatically find the latest config.yml generated by the training run
CONFIG_PATH=$(find outputs_three_flat/three_flat_real_calib/nerfacto -name "config.yml" | sort | tail -n 1)

if [ -z "$CONFIG_PATH" ]; then
    echo "Error: Could not find config.yml. Did training fail?"
    exit 1
fi

echo "Found latest training config: $CONFIG_PATH"
echo "Running tightly cropped point cloud export..."

# Must explicitly include --obb-rotation 0.0 0.0 0.0 or the bounding box will be completely ignored
.venv_nerf/bin/ns-export pointcloud \
    --load-config "$CONFIG_PATH" \
    --output-dir exports/three_flat_pc_cropped \
    --num-points 1000000 \
    --remove-outliers True \
    --normal-method open3d \
    --obb-center 0.0 0.0 0.0 \
    --obb-scale 3.33 3.33 3.33 \
    --obb-rotation 0.0 0.0 0.0

echo ""
echo "========================================="
echo "4. Filtering Point Cloud (SOR)"
echo "========================================="
.venv_nerf/bin/python tools/nerf/filter_cloud.py \
    --input exports/three_flat_pc_cropped/point_cloud.ply \
    --output exports/three_flat_pc_cropped/point_cloud_filtered.ply

echo "========================================="
echo "Pipeline complete! Final filtered mesh saved to exports/three_flat_pc_cropped/point_cloud_filtered.ply"
echo "========================================="
