#!/bin/bash
set -e

echo "====================================="
echo " 🖼️ Downloading Poster Dataset "
echo "====================================="
# The standard blender lego dataset is hosted on Google Drive, which often fails due to quota limits on VMs.
# We download the official 'poster' dataset instead, which is hosted on S3 and always works!
.venv_nerf/bin/ns-download-data nerfstudio --capture-name poster

echo "====================================="
echo " 🚀 Starting NeRF Training           "
echo "====================================="
# Train nerfacto model. We cap the iterations at 2000 so you don't have to wait all day to see the PLY.
.venv_nerf/bin/ns-train nerfacto \
    --data data/nerfstudio/poster \
    --machine.num-devices 1 \
    --max-num-iterations 2000 \
    --vis tensorboard 

echo "====================================="
echo " ☁️ Exporting Point Cloud (.ply)      "
echo "====================================="
# Find the latest config file generated by the training
CONFIG_FILE=$(ls -t outputs/poster/nerfacto/*/config.yml | head -n 1)

if [ -z "$CONFIG_FILE" ]; then
    echo "Error: Could not find config.yml. Training may have failed."
    exit 1
fi

echo "Found config file: $CONFIG_FILE"

# Export the point cloud
mkdir -p tools/nerf/output_poster
.venv_nerf/bin/ns-export pointcloud \
    --load-config "$CONFIG_FILE" \
    --output-dir tools/nerf/output_poster \
    --num-points 1000000 \
    --remove-outliers True \
    --use-bounding-box True \
    --bounding-box-min -1.5 -1.5 -1.5 \
    --bounding-box-max 1.5 1.5 1.5

echo "====================================="
echo " ✅ Done! PLY saved in tools/nerf/output_poster/ "
echo "====================================="
